### ISSUE TITLE
Rename Column Headers in Extracted SNAP data

### ISSUE THREAD

**Issue by pafrank89** [pafrank89/AlaskaShrubs#1]
I am trying to rework the following code that Kata developed to extract CRU TS V4.3 data from  sample points, so that it will extract data from the my AK specific UAF SNAP climate data. 

[https://github.com/pafrank89/AlaskaShrubs/blob/master/R_Script/ClimateData_Extract.R](url)
**Lines 117-127

After extracting data we want to rename the column headings. The CRU TS V4.3 data is organized starting 1901 progressing through the months from January to December for each year up to 2015 (ex. 1901-Jan, 1901-Feb, 1901-Mar ect...)

To do that the code looks like this: 

`years <- 1901:2015`

` month <- c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")`

`names(snap.pre.shrubs) <- paste(rep(years, each=12), rep(month, times=113), sep="_")`

The SNAP data is structured by month, so it starts with all the January values between 1901 and 2015 (ex. 1901-Jan, 1902-Jan, 1903-Jan, ect...) So I need to rework this so that the columns in the snap data are correctly renamed, but am unsure after looking at the documentation for [paste](https://www.rdocumentation.org/packages/base/versions/3.6.1/topics/paste) and [rep](https://www.rdocumentation.org/packages/base/versions/3.6.1/topics/rep), that I understand how to update this code to make it work. 

Thanks for your help!

**Comment by JamesDMSpeed** [comment]
If I understand correctly, try
eg<-expand.grid(years,month)
monyr<-paste(eg$Var2,eg$Var1,sep='-')

**Comment by pafrank89** [comment]
That's perfect! 

Thank you James
