### ISSUE TITLE
Color Threshold in color2D.matplot 

### ISSUE THREAD

**Issue by pafrank89** [pafrank89/AlaskaShrubs#2]
In the appendix I have three figures which represent the backward selection process, showing when non-significant parameters were eliminated. I am using colors to represent the p-value, and currently I am using a continuous scale from blue (low p-values) to red (high p-values). James brought up a great point that there should be a threshold 

The code for these graphs is on my GitHub at AlaskaShrubs/R_Script/Thesis_Figures.R. The code for these figures begins at line 924, but I've pasted the pertinent code for one of the plots here. The data is located at AlaskaShrubs/R_Data/ModelSelection_Betula.csv and is just a dataframe containing the p-values from the Wald test at each iteration of backward selection. 

`par(mar = c(5,12,5,2) + 0.1)`

`color2D.matplot(ModelSelection_Betula, `
               `vcol = "White", na.color = "White",`
                `extremes = c("dodgerblue4","firebrick3"),`
                `nslices = 50,`
                `show.legend=TRUE, show.values=4,`
                `axes=FALSE, xlab="", ylab="")`

`axis(3,at=0.5:2,las=1,labels=c("Full\n Model", "Minimal\nAdequate\nModel"))`
`axis(2,at=0.5:6,las=2,labels=c("Snowshow Hare :\nMean SummerTemperature\nInteraction",`
                               `"Moose :\nMean Summer Temperature\nInteraction",`
                              ` "Snowshoe Hare\nIndex", "Moose Density", `
                               `"Mean Summer\nPrecipitation", "Mean Summer\nTemperature"))`

`mtext('Betula nana Model Selection', side=3, line=3, padj = 2, at = -.35, cex = 1.25)`

Here is the vignette for [color2D.matplot](https://www.rdocumentation.org/packages/plotrix/versions/3.7-7/topics/color2D.matplot). Making a threshold is clearly possiable as they mention it in the examples with this code here: 

`# generate colors that show negative values in red to brown`
` # and positive in blue-green to green`
` cellcol<-matrix(rep("#000000",100),nrow=10)`
` cellcol[x<0]<-color.scale(x[x<0],c(1,0.8),c(0,0.8),0)`
` cellcol[x>0]<-color.scale(x[x>0],0,c(0.8,1),c(0.8,0)) `

I can rework this code so that when p>0.05 scale is blue and p<0.05 scale is red; but don't know how to then get that color distinction into the color2D.matplot function so that it is reflected in the figure?

Thanks in advance for your help!!
Peter

**Comment by JamesDMSpeed** [comment]
If I read correcty then you have changed the x[x<0] and x[x>0] sections to 0.05?
You then need to specify that the colour scale used is that you defined (add the argument cellcolors=cellcol to the color3dmatplot function)

**Comment by pafrank89** [comment]
Thanks James, 

I think I have it figured out. Does this look better?
![image](https://user-images.githubusercontent.com/48218711/81310785-dc0ace80-9084-11ea-9a3b-8294d0abe32c.png)
`cellval_b<-matrix(as.numeric(unlist(ModelSelection_Betula)))`

`cellval_b[is.na(cellval_b)] <- 0`

`cellcol_b = matrix(rep("#000000",12),nrow=12)`

`cellcol_b[cellval_b<0.05]<-color.scale(cellval_b[cellval_b<0.05], extremes = ``c("dodgerblue4","dodgerblue")) `

`cellcol_b[cellval_b>0.05]<-color.scale(cellval_b[cellval_b>0.05],extremes = ``c("firebrick1","firebrick4")) `

`cellcol_b[cellcol_b == "#104E8BFF"] <- NA`

`color2D.matplot(ModelSelection_Betula, `
`                vcol = "White", na.color = "White",`
`                cellcolors= cellcol_b,`
`                nslices = 50,`
`                show.legend=TRUE, show.values=4,`
`                axes=FALSE, xlab="",ylab="")`

**Comment by JamesDMSpeed** [comment]
Looks good!
